// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWXNVlsZUqra2Ym3KFxb0mPjaWhC9YjJo',
    appId: '1:440087069541:web:58a8f330af99998eb3d78c',
    messagingSenderId: '440087069541',
    projectId: 'yumesprout-7b830',
    authDomain: 'yumesprout-7b830.firebaseapp.com',
    storageBucket: 'yumesprout-7b830.firebasestorage.app',
    measurementId: 'G-Y1ZJEDD1BJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUrm3fLp6ToOJiLJrDetZ2uSlAIW77rj4',
    appId: '1:440087069541:ios:0b25abfec05aad69b3d78c',
    messagingSenderId: '440087069541',
    projectId: 'yumesprout-7b830',
    storageBucket: 'yumesprout-7b830.firebasestorage.app',
    iosBundleId: 'com.example.yumesproutV4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUrm3fLp6ToOJiLJrDetZ2uSlAIW77rj4',
    appId: '1:440087069541:ios:0b25abfec05aad69b3d78c',
    messagingSenderId: '440087069541',
    projectId: 'yumesprout-7b830',
    storageBucket: 'yumesprout-7b830.firebasestorage.app',
    iosBundleId: 'com.example.yumesproutV4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWXNVlsZUqra2Ym3KFxb0mPjaWhC9YjJo',
    appId: '1:440087069541:web:4b994c3a61b645ceb3d78c',
    messagingSenderId: '440087069541',
    projectId: 'yumesprout-7b830',
    authDomain: 'yumesprout-7b830.firebaseapp.com',
    storageBucket: 'yumesprout-7b830.firebasestorage.app',
    measurementId: 'G-SJHVB2HGD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGiHAsb8Xjiyzj9r8LFJ-TnWGDk1m_k8A',
    appId: '1:440087069541:android:90eaa8a53394afbfb3d78c',
    messagingSenderId: '440087069541',
    projectId: 'yumesprout-7b830',
    storageBucket: 'yumesprout-7b830.firebasestorage.app',
  );
}
